# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

services:
    App\Discord\DiscordApiClientInterface:
        public: true
        alias: App\Discord\DiscordHttpApiClient

    App\Discord\DiscordGuildResourcesProviderInterface:
        public: true
        alias: App\Discord\DiscordGuildResourcesProvider
